### ISSUE TITLE
Friends

### ISSUE THREAD

**Issue by jake-shasteen** [InterruptedLobster/findAR#18]
As a user I would like to be able to give specific people permission to view some extra data about me.
# checklist
### #36
* Log in with facebook
* Create a reference to the firebase store of that user's data
  * Perhaps change store by adding callback function to db.js
* Sync redux store with firebase data for that individual user

### #17
* Create a component to toggle whether someone should be able to send me pins
* Create a component to send a pin to a friend Only allow sending to friends who have the option enabled
* Add sent pins to user's pins {} but tag them as 'friend' pins

### #22, #23
* Create a component to hide or show a given pin
* Filter hidden pins from map and AR props

### #14
* Modify mapView to differentiate my pins from my friend's pins.

### #16
* Modify AR View to differentiate my pins from my friend's pins

### #82
* Modify List View to differentiate my pins from my friend's pins

### #81
* Filter by friends only
  * Add component to toggle this option
  * When option is toggled, data sent to rendering components is limited to friend's pins only. This should not actually modify the pins in the redux store?

**Comment by jake-shasteen** [comment]
I'm thinking a good data structure for pins might be:
```
pins: {
  <pinID>: {
    longitude: NUMBER
    latitude: NUMBER
    title: STRING
    friend: BOOL
  }
friends: {
  0: NUMBER (friend id)
  ...
  N: NUMBER ( friend id )
}
```

**Comment by bignell** [comment]
Excellent. Are the keys of the `friends` obj a simple count index? And can you elaborate a little on how you'd implement filtering?
